Version 0.31

diff --git a/escm/configure b/escm/configure
--- a/escm/configure
+++ b/escm/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE DEFAULT_LANG SCHEME with_backend ESCM_BACKEND CPP EGREP LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE DEFAULT_LANG SCHEME CGI_TOOL CGIBIN CPP EGREP LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -857,7 +857,7 @@ Optional Packages:
   --with-default=lang   specify the default language (scm).
   --with-scheme           the default scheme program and its arguments (gosh
                           -b)
-  --with-backend="interpreter arg ... "   specify the backend interpreter (gosh).
+  --with-cgibin=DIR       the cgi-bin directory.
 
 Some influential environment variables:
   CC          C compiler command
@@ -3023,112 +3023,34 @@ _ACEOF
 # Check whether --with-scheme or --without-scheme was given.
 if test "${with_scheme+set}" = set; then
   withval="$with_scheme"
-
-fi;
-if test "$with_scheme" = "yes" || test "$with_scheme" = ""; then
+  if test "$withval" = "yes" ; then
    SCHEME="gosh -b"
-elif test "$with_default" = "no"; then
+elif test "$withval" = "no" || test "$withval" = ""; then
    SCHEME="guile -s /dev/stdin"
 else
-   SCHEME="$with_scheme"
+   SCHEME="$withval"
 fi
+else
+  SCHEME="guile -s /dev/stdin"
+fi;
 
 
-# Checks for the backend interpreter.
 
-# Check whether --with-backend or --without-backend was given.
-if test "${with_backend+set}" = set; then
-  withval="$with_backend"
+# Check whether --with-cgibin or --without-cgibin was given.
+if test "${with_cgibin+set}" = set; then
+  withval="$with_cgibin"
+  if test "$withval" = "yes" || test "$withval" = ""; then
+  { { echo "$as_me:$LINENO: error: \"--with-cgibin=DIR -- requires a directory.\"
+See \`config.log' for more details." >&5
+echo "$as_me: error: \"--with-cgibin=DIR -- requires a directory.\"
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+CGIBIN=$withval
+CGI_TOOL=aescm.cgi
+
 
 fi;
-if test "$with_backend" = "no"; then
-  { { echo "$as_me:$LINENO: error: The backend interpreter required." >&5
-echo "$as_me: error: The backend interpreter required." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test "$DEFAULT_LANG" = "scm"; then
-  if test "$with_backend" = "yes" || test "$with_backend" = ""; then
-    with_backend=
-    for ac_prog in gosh guile
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_with_backend+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$with_backend"; then
-  ac_cv_prog_with_backend="$with_backend" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_with_backend="$ac_prog"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-fi
-fi
-with_backend=$ac_cv_prog_with_backend
-if test -n "$with_backend"; then
-  echo "$as_me:$LINENO: result: $with_backend" >&5
-echo "${ECHO_T}$with_backend" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-  test -n "$with_backend" && break
-done
-
-  fi
-fi
-if test "$with_backend" != ""; then
-  backend_path=`echo $with_backend | sed -e "s/ .*//"`
-  backend_args=`echo $with_backend | sed -e "s/^[^ ]*//"`
-# add the default arguments.
-  if test "$backend_path" = "gosh" -a "$backend_args" = ""; then
-    backend_args=" -b"
-  elif test "$backend_path" = "guile" -a "$backend_args" = ""; then
-    backend_args=" -s /dev/stdin"
-  fi
-  backend_path=`which $backend_path`
-  as_ac_File=`echo "ac_cv_file_$backend_path" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for $backend_path" >&5
-echo $ECHO_N "checking for $backend_path... $ECHO_C" >&6
-if eval "test \"\${$as_ac_File+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "$backend_path"; then
-  eval "$as_ac_File=yes"
-else
-  eval "$as_ac_File=no"
-fi
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
-
-  backend_prog="$backend_path$backend_args"
-  ESCM_BACKEND=$backend_prog
-
-cat >>confdefs.h <<_ACEOF
-#define ESCM_BACKEND "$backend_prog"
-_ACEOF
-
-  fi
-
 
 # Checks for libraries.
 # Checks for header files.
@@ -4738,8 +4660,8 @@ s,@am__fastdepCC_TRUE@,$am__fastdepCC_TRUE,;t t
 s,@am__fastdepCC_FALSE@,$am__fastdepCC_FALSE,;t t
 s,@DEFAULT_LANG@,$DEFAULT_LANG,;t t
 s,@SCHEME@,$SCHEME,;t t
-s,@with_backend@,$with_backend,;t t
-s,@ESCM_BACKEND@,$ESCM_BACKEND,;t t
+s,@CGI_TOOL@,$CGI_TOOL,;t t
+s,@CGIBIN@,$CGIBIN,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
